# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:     
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output  # create output dir
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
        name: tcyrus/homebrewery-standalone
      - run: npm install
      - run: npm run hb -- README.md output/result.pdf
      #- uses: docker://pandoc/latex:2.9
        #with:
          #args: --output=output/result.pdf README.md
      - uses: actions/upload-artifact@main
        with:
          name: myartifact
          path: output/result.pdf
