









# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:     
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
        name: tcyrus/homebrewery-standalone
        with:
          path: homebrewery
      - run: npm install https://github.com/Nioux/homebrewery-standalone
      - run: npm run hb -- README.md README.pdf
      - uses: actions/upload-artifact@main
        with:
          name: myartifact
          path: README.pdf









